[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "synthshell_core"
version = "1.0.0"
authors = [
  { name="subnarcher" },
]
description = "A background and emergency shell framework for Python automation"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/subnarcher/SynthShell/tree/main"
